#!/bin/bash

# Export Azure environment variables to match Streamlit's expected format
export AIPROJECT_CONNECTION_STRING="$AIPROJECT_CONNECTION_STRING"
export AISEARCH_INDEX_NAME="$AISEARCH_INDEX_NAME"
export AISEARCH_ENDPOINT="$AISEARCH_ENDPOINT"
export AISEARCH_KEY="$AISEARCH_KEY"
export EMBEDDINGS_MODEL="$EMBEDDINGS_MODEL"
export INTENT_MAPPING_MODEL="$INTENT_MAPPING_MODEL"
export CHAT_MODEL="$CHAT_MODEL"
export EVALUATION_MODEL="$EVALUATION_MODEL"
export BLAND_API_KEY="$BLAND_API_KEY"

# Create secrets.toml dynamically
mkdir -p /root/.streamlit
cat > /root/.streamlit/secrets.toml << EOL
# Azure AI Project Connection
AIPROJECT_CONNECTION_STRING = "${AIPROJECT_CONNECTION_STRING}"

# Azure Search Configuration  
AISEARCH_INDEX_NAME = "${AISEARCH_INDEX_NAME}"
AISEARCH_ENDPOINT = "${AISEARCH_ENDPOINT}"
AISEARCH_KEY = "${AISEARCH_KEY}"

# Model Settings
EMBEDDINGS_MODEL = "${EMBEDDINGS_MODEL}"
INTENT_MAPPING_MODEL = "${INTENT_MAPPING_MODEL}"
CHAT_MODEL = "${CHAT_MODEL}"
EVALUATION_MODEL = "${EVALUATION_MODEL}"

# Bland AI
BLAND_API_KEY = "${BLAND_API_KEY}"
EOL

# Start Streamlit
streamlit run app.py --server.port 8000 --server.address 0.0.0.0 